name-template: "web-api/$PATCH"
tag-template: "web-api/$PATCH"
version-template: "0.0.$PATCH"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-resolver:
  default: patch
template: |
  ## Changes

  $CHANGES
